# docker-compose.yml
version: "3.7"
services:
  simpleserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: abc/def
    networks:
      - dev-network
      
  wireshark:
    image: lscr.io/linuxserver/wireshark:3.4.13
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/me/wireshark:/config
    ports:
      - 3000:3000 #optional
    #   - 4822:4822 #optional
    restart: unless-stopped
    networks:
      - dev-network

networks:
  dev-network:
    external: true