// #include <bzlib.h>
// #define UINT16_MAX 0xffff       /* 65535U */
// #include <stdint.h>

// // #include "bacnet-stack/src/bacnet/bacdef.h"
// // #include "bacnet-stack/src/bacnet/datalink/datalink.h"
// // #include "bacnet-stack/src/bacnet/apdu.h"
// // #include "../bacnet-stack/src/bacnet/bacenum.h"
#include "../bacnet-stack/src/bacnet/bacdef.h"
#include "../bacnet-stack/src/bacnet/config.h"
#include "../bacnet-stack/src/bacnet/bactext.h"
#include "../bacnet-stack/src/bacnet/bacerror.h"
#include "../bacnet-stack/src/bacnet/iam.h"
#include "../bacnet-stack/src/bacnet/arf.h"
#include "../bacnet-stack/src/bacnet/basic/tsm/tsm.h"
#include "../bacnet-stack/src/bacnet/basic/binding/address.h"
#include "../bacnet-stack/src/bacnet/npdu.h"
#include "../bacnet-stack/src/bacnet/apdu.h"
#include "../bacnet-stack/src/bacnet/basic/object/device.h"
#include "../bacnet-stack/src/bacnet/datalink/datalink.h"
#include "../bacnet-stack/src/bacnet/whois.h"
#include "../bacnet-stack/src/bacnet/version.h"
#include "../bacnet-stack/src/bacnet/basic/sys/filename.h"
#include "../bacnet-stack/src/bacnet/basic/services.h"
#include "../bacnet-stack/src/bacnet/basic/tsm/tsm.h"
#include "../bacnet-stack/src/bacnet/datalink/dlenv.h"
//// #include "bacport.h"